sudo: required
dist: trusty
group: edge
language: php

php:
  - 5.6
  - 7.1
  - hhvm

matrix:
  fast_finish: true

before_script:
  - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - composer self-update
  - composer install --no-interaction
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'hhvm.php7.all = 1' >> /etc/hhvm/php.ini; fi

script:
  - vendor/bin/kahlan
